# Generated by Django 4.2.1 on 2023-06-06 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instructor_id',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='course_id',
            new_name='course',
        ),
    ]
