# Generated by Django 4.2.1 on 2023-05-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_instructor_id_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='Unilearn\\profile_pictures'),
        ),
    ]
